nationalities = ['Russia', 'USA', 'Europe']

genres = ['chill',
          'classical',
          'club',
          'dance',
          'deep-house',
          'detroit-techno',
          'disco',
          'disney',
          'drum-and-bass',
          'dub',
          'dubstep',
          'edm',
          'electro',
          'house',
          'minimal-techno',
          'pop',
          'progressive-house',
          'punk-rock',
          'r-n-b',
          'rock',
          'techno',
          'trance']

tracks = [['HOSH', 'Tighter (feat. Jalja) [CamelPhat Remix]', 234],
          ['Eli & Fur', 'Otherside (Nils Hoffmann Remix)', 219],
          ['Cristoph', 'Out Of Reach', 256],
          ['Robbie Williams', 'Life Thru A Lens', 265],
          ['Red Hot Chili Peppers', 'Californication (Deluxe Edition)', 255],
          ['MiyaGi & Endspiel', 'Неизданное, Pt. 1', 206],
          ['Tipsi Tip', 'Шторит', 201],
          ['Legendy Pro', 'Легенды Про...Centr', 286],
          ['D.Cure', 'Cuz It Bangz 6', 320],
          ['Pop Smoke', 'Meet The Woo', 200],
          ['Pop Smoke', 'Meet The Woo 2', 128],
          ['Pop Smoke', 'Shoot For The Stars Aim For The Moon (Deluxe)', 213],
          ['Gunna', 'DS4EVER', 168],
          ['MiyaGi & Endspiel', 'Untouchable', 213],
          ['Miyagi & Andy Panda', 'Буревестник', 247],
          ['Султан Лагучев', 'Между нами война', 181],
          ['Hot Since 82', "Buggin", 506],
          ['Miyagi & Andy Panda', 'Не жалея', 214],

          ['MiyaGi', 'Buster Keaton', 214],
          ['Miyagi & Andy Panda', 'Kosandra', 221],
          ['Housenick', 'No One', 299],
          ['Catching Flies', 'GLY', 221],
          ['Matvey Emerson', 'Say My Name', 213],
          ['9 Gramm', 'One Love', 216],
          ['Max Korzh', 'Жить в кайф', 174],
          ['CamelPhat', 'One Hump or Two', 432],
          ['Hot Since 82', '8-track', 358],
          ['Curren$y', 'Covert Coup', 187],
          ['Onyx', 'Triggernometry', 203],
          ['Xzibit', 'Serial Killers: Day of the Dead', 182],
          ['Dave East', 'Karma 3', 173],
          ['Maceo Plex', 'Love Somebody Else / Future Musik', 494],
          ['Jan Blomqvist', 'Our Broken Mind Embassy (Boris Brejcha Remix)', 460],
          ['Darin Epsilon', 'My Own Time (Miss Monique Remix)', 425],
          ['Rick Ross', 'Outlawz (feat. Jazmine Sullivan & 21 Savage)', 290],
          ['Miyagi & Andy Panda', 'Marmalade', 220],
          ['ATL', 'Марабу', 198],
          ['Max Korzh', 'Не твой', 175],
          ['SLIMUS', 'Самбо Белого Мотылька', 191],
          ['Moneybagg Yo', 'A Gangsta’s Pain: Reloaded', 241],
          ['Café del Mar', 'Café del Mar Terrace Mix 8', 296],
          ['Quavo', 'Strub Tha Ground (Feat. Yung Miami)', 195],
          ['Gucci Mane', 'So Icy Boyz', 218],
          ['Young Thug', 'Punk', 165],
          ['Pouya', 'Blood Was Never Thick As Water', 123],
          ['Wu-Tang Clan', 'Wu-Tang Iron Flag', 274],
          ['Amtrac', 'True Value', 348],
          ['Late Night Alumni', 'Empty Streets (Remixes)', 501],
          ['EPMD', 'Back In Business', 208],
          ['M.O.P.', 'Warriorz', 244],
          ['Dave East', 'HOFFA', 146],
          ['Elton John', 'Cold Heart (Claptone Remix)', 184],
          ['Russ', 'Utah Freestyle', 187],
          ['James Grant', 'The Anjunadeep Edition 308', 315],
          ['Booka Shade', 'To the Sea', 452],
          ['Рыночные Отношения', '2021', 216],
          ['Onyx', "Shut Em Down", 239],
          ['Брутто', 'ГАДДЕМ 2', 210],
          ['J. Cole', 'The Off-Season', 219],
          ['Evgeny Kutsenok', 'Russian Soul / Peshavar', 328],
          ['Logic', 'Bobby Tarantino II', 189],
          ['Hurts', 'Redemption (Kolya Funk Remix)', 159],
          ['JAHMED', 'Armani', 127],
          ['Outkast', 'Speakerboxxx/The Love Below', 370],
          ['Tyga', 'Ayy Macarena', 132],
          ['Desiigner', '3 THE HARD WAY', 140],
          ['Klanglos', 'I Can Feel the Pain', 482],
          ['Stil & Bense', 'Untold', 402],
          ['Tale Of Us', 'Unity Pt. 2', 488],
          ['Fritz Kalkbrenner', 'Golden (Fideles Remix)', 238],
          ['Eminem', 'The Marshall Mathers LP', 288],
          ['Gorgon City', 'Olympia', 207],
          ['Drake', 'Scorpion', 218],
          ['LOL Boys', 'Changes - EP', 322],
          ['Awon', 'Sleep Is the Cousin of Death', 155],
          ['Jan Blomqvist', 'Remote Control (Remixed)', 494],
          ['Fabrication', 'SPLIT 02', 368],
          ['Sono', 'Keep Control (ARTBAT Remix)', 484],
          ['Sofi Tukker', 'House Arrest', 216],
          ['ARTBAT', 'Best of Me', 553],
          ['Cut Snake', 'Change Will Come', 266],
          ['CamelPhat', 'For a Feeling (feat. RHODES) [Layton Giordani Remix]', 484],
          ['Booka Shade', 'Blaze', 410],
          ['ARTBAT', 'Papillon', 426],
          ['ARTBAT', 'Best of Me (Radio Edit)', 229],
          ['Above & Beyond', 'The Club Mix Collection', 363],
          ['CamelPhat', 'Breathe', 194],
          ['Tube & Berger', 'All I Want (feat. Goatchy)', 225],
          ['ATB', 'Future Memories', 304],
          ['ATB', 'No Silence', 261],
          ['CamelPhat', 'For a Feeling (feat. RHODES)', 296],
          ['Wu-Tang Clan', 'Wu-Tang Forever', 338],
          ['Индаблэк', 'Плохие привычки', 243],
          ['ATL', 'Гелиоз', 202],
          ['Scorpions', 'Crazy World', 312],
          ['Basta', '40', 311],
          ['Wu-Tang Clan', 'The Saga Continues', 234],
          ['SLIMUS', 'Новичок', 250],
          ['Kasta', 'Четырёхглавый Орёт', 290],
          ['Smoky Mo', 'День первый', 257],
          ['9 Gramm', 'Чёрный', 193],
          ['Triada', 'Исток', 198],
          ['Loc-Dog', 'Растает', 212],
          ['Drummatix', 'Туманами', 201],
          ['Dion', 'Runaround Sue (Original Album Plus Bonus Tracks)', 173],
          ['Samir Kuliev', 'Want Your Back', 472],
          ['Boris Brejcha', 'Lost Memory', 463],
          ['Passenger 10', 'Age of Discovery', 246],
          ['Eran Hersh', 'Human', 412],
          ['Marc Holstege', 'Marc Holstege | Jaquomo', 393],
          ['Klangkarussell', 'Home / Air', 225],
          ['Schiller', 'Morgenstund', 286],
          ['Zarasko', 'Love Tonight (Remix)', 154],
          ['21 Savage', 'i am > i was', 195],
          ['Future', 'FUTURE', 205],
          ['Mike WiLL Made-It', '23', 253],
          ['Bazanji', '2019', 112],
          ['Horse Meat Disco', 'Jump Into The Light', 284],
          ['Colette', 'Hotwire', 309],
          ['Monolink', 'Return to Oz (ARTBAT Remix)', 480],
          ['Solomun', 'Black Label #36', 446],
          ['Nigativ', 'Простой', 229],
          ['Russ', 'Pink Elephant', 253],
          ['Kendrick Lamar', 'DAMN.', 186],
          ['21 Savage', 'Without Warning', 269],
          ['Migos', 'Culture III', 213],
          ['Polo G', 'Hall of Fame', 265],
          ['Skepta', 'Konnichiwa', 186],
          ['Kendrick Lamar', 'good kid, m.A.A.d city (Deluxe)', 350],
          ['Miss Monique', 'Proton Sessions 001 (DJ Mix)', 346],
          ['Migos', 'Culture II', 288],
          ['Lil Baby', 'The Voice of the Heroes', 218],
          ['Young Thug', 'So Much Fun (Deluxe)', 211],
          ['DaBaby', 'Blank Blank', 79],
          ['GUF', 'Лето на ветер', 260],
          ['Truwer', 'КАЗ.ПРАВДЫ', 231],
          ['MiyaGi & Endspiel', 'DLBM', 154],
          ['GUF', 'Дом, который построил Алик', 270],
          ['Skryptonite', 'Свистки и бумажки', 218],
          ['MiyaGi & Endspiel', 'Hajime, Pt. 1', 186],
          ['Miyagi & Andy Panda', 'YAMAKASI', 209],
          ['Young Nudy', 'DR. EV4L', 186],
          ['Boris Brejcha', 'Schaltzentrale (Joker Remake)', 517],
          ['Miss Monique', "Dont Come Back (feat. JOSEFINA)", 285],
          ['Claptone', 'Fantast', 194],
          ['DJ Khaled', 'KHALED KHALED', 237],
          ['Pooh Shiesty', 'Shiesty Season - Spring Deluxe', 192],
          ['Future', 'Life Is Good (feat. Drake, DaBaby & Lil Baby) [Remix]', 315],
          ['J. Cole', 'Lewis Street', 211],
          ['Jack Harlow',
           'WHATS POPPIN (feat. DaBaby, Tory Lanez & Lil Wayne) [Remix]',
           227],
          ['Mike WiLL Made-It', 'Ransom 2', 275],
          ['Stunna 4 Vegas', 'UP THE SMOKE (with Offset)', 188],
          ['JACKBOYS', 'JACKBOYS', 158],
          ['Migos', 'Culture', 343],
          ['Nicki Minaj', 'Beam Me Up Scotty', 340]]

albums = [['HOSH', 'Midnight (The Hanging Tree) [Remixes]', '2020'],
          ['Eli & Fur', 'Found In The Wild (Remixed)', '2021'],
          ['Cristoph', '8-track', '2016'],
          ['Robbie Williams', 'The Christmas Present (Deluxe)', '2020'],
          ['Red Hot Chili Peppers', 'The Getaway', '2016'],
          ['MiyaGi & Endspiel', 'Неизданное, Pt. 1', '2020'],
          ['Tipsi Tip', 'ДАТЫНЕТ', '2018'],
          ['Legendy Pro', 'Классики', '2014'],
          ['D.Cure', 'Cuz It Bangz 6', '2021'],
          ['Pop Smoke', 'Faith (Deluxe)', '2021'],
          ['Gunna', 'DRIP SEASON 4EVER', '2022'],
          ['Miyagi & Andy Panda', 'YAMAKASI', '2020'],
          ['Султан Лагучев', 'Люблю и ненавижу', '2022'],
          ['Hot Since 82', 'Recovery', '2020'],
          ['MiyaGi', 'Buster Keaton', '2019'],
          ['Housenick', 'On Falling', '2021'],
          ['Catching Flies', 'Silver Linings Remixed', '2020'],
          ['Matvey Emerson', 'Slipping Through', '2021'],
          ['9 Gramm', 'Чёрный', '2020'],
          ['Max Korzh', 'Психи попадают в топ', '2021'],
          ['CamelPhat', 'Dark Matter', '2020'],
          ['Curren$y', 'Pilot Talk 4', '2021'],
          ['Onyx', '14 Jazz Standards', '2021'],
          ['Xzibit', 'Serial Killers Presents: Summer of Sam', '2020'],
          ['Dave East', 'HOFFA', '2021'],
          ['Maceo Plex', 'Mutant Series', '2019'],
          ['Jan Blomqvist', 'Disconnected - Live in Munich', '2020'],
          ['Darin Epsilon', 'WE ARE KATERMUKKE: Darin Epsilon (DJ Mix)', '2021'],
          ['Rick Ross', 'Richer Than I Ever Been', '2021'],
          ['ATL', 'Радио Апокалипсис', '2021'],
          ['SLIMUS', 'Самбо Белого Мотылька', '2021'],
          ['Moneybagg Yo', 'A Gangsta’s Pain: Reloaded', '2021'],
          ['Café del Mar', 'Café del Mar - Terrace Mix 11 (DJ Mix)', '2021'],
          ['Quavo', 'QUAVO HUNCHO', '2018'],
          ['Gucci Mane', 'So Icy Christmas', '2021'],
          ['Young Thug', 'Punk', '2021'],
          ['Pouya', 'Blood Was Never Thick As Water', '2021'],
          ['Wu-Tang Clan',
           'Of Mics and Men (Music from the Showtime Documentary Series)',
           '2019'],
          ['Amtrac', 'Oddyssey', '2020'],
          ['Late Night Alumni', 'Silver', '2019'],
          ['EPMD', 'The Instrumentals', '2020'],
          ['M.O.P.', 'Street Certified', '2014'],
          ['Elton John', 'The Lockdown Sessions', '2021'],
          ['Russ', 'CHOMP 2', '2021'],
          ['James Grant', 'The Anjunadeep Edition 360 with James Grant', '2021'],
          ['Booka Shade', 'Both', '2021'],
          ['Рыночные Отношения', '2021', '2021'],
          ['Брутто', 'ГАДДЕМ 2', '2021'],
          ['J. Cole', 'The Off-Season', '2021'],
          ['Evgeny Kutsenok', 'Desert Voyage', '2021'],
          ['Logic', 'Bobby Tarantino III', '2021'],
          ['Hurts', 'Faith', '2020'],
          ['JAHMED', 'Armani', '2021'],
          ['Outkast', 'ATLiens (25th Anniversary Deluxe Edition)', '2021'],
          ['Tyga', 'Legendary (Deluxe Edition)', '2019'],
          ['Desiigner', 'L.O.D.', '2018'],
          ['Klanglos', 'The Breakdown', '2020'],
          ['Stil & Bense', 'Lost & Found EP (feat. kATTA)', '2015'],
          ['Tale Of Us', 'Unity (Voyage Mix)', '2020'],
          ['Fritz Kalkbrenner', 'True Colours', '2020'],
          ['Eminem', 'Music To Be Murdered By - Side B (Deluxe Edition)', '2020'],
          ['Gorgon City', 'Olympia (Remixes)', '2021'],
          ['Drake', 'Certified Lover Boy', '2021'],
          ['LOL Boys', 'LDR', '2011'],
          ['Awon', 'Nothing Less', '2021'],
          ['Fabrication', 'Colors', '2020'],
          ['Sono', '20 Years - The Singles 2000 - 2020', '2020'],
          ['Sofi Tukker', 'Treehouse (Japan Version)', '2018'],
          ['ARTBAT', 'Age of Love (ARTBAT Rave Mix)', '2022'],
          ['Cut Snake', 'Switch Up', '2020'],
          ['Above & Beyond', 'Group Therapy 468', '2022'],
          ['Tube & Berger', 'We Are All Stars Remixes Part II', '2018'],
          ['ATB', 'Next', '2017'],
          ['Индаблэк', 'Плохие привычки', '2021'],
          ['Scorpions', 'Return to Forever (Tour Edition)', '2016'],
          ['Basta', '40 (Инструментальная версия)', '2021'],
          ['Kasta', 'Альбомба', '2021'],
          ['Smoky Mo', 'Super Mario', '2020'],
          ['Triada', 'Лучшее', '2018'],
          ['Loc-Dog', 'Счастье в простом', '2021'],
          ['Drummatix', 'Рубикон (Instrumentals)', '2021'],
          ['Dion', 'Stomping Ground', '2021'],
          ['Samir Kuliev', 'Gently Weeps', '2021'],
          ['Boris Brejcha', 'Never Stop Dancing', '2021'],
          ['Passenger 10', 'Reset Your Mind', '2019'],
          ['Eran Hersh', 'Ibiza 2010 House Room', '2010'],
          ['Marc Holstege', 'Marc Holstege | Jaquomo', '2020'],
          ['Klangkarussell', 'Faze #70: Klangkarussell', '2018'],
          ['Schiller', 'Epic (Deluxe)', '2021'],
          ['Zarasko', 'House Music (Extended version)', '2021'],
          ['21 Savage', 'SAVAGE MODE II [CHOPPED NOT SLOPPED]', '2020'],
          ['Future', 'Pluto x Baby Pluto (Deluxe)', '2020'],
          ['Mike WiLL Made-It', 'Creed II: The Album', '2018'],
          ['Bazanji', 'Far From Normal', '2021'],
          ['Horse Meat Disco', 'Love And Dancing', '2020'],
          ['Colette', 'The Pete Moss Remixes', '2020'],
          ['Monolink', 'Under Darkening Skies', '2021'],
          ['Solomun', 'Nobody Is Not Loved', '2021'],
          ['Nigativ', 'Либератта', '2021'],
          ['Kendrick Lamar',
           'Black Panther The Album Music From And Inspired By',
           '2018'],
          ['Migos', 'Culture III (Deluxe)', '2021'],
          ['Polo G', 'Hall of Fame 2.0', '2021'],
          ['Skepta', 'Insomnia', '2020'],
          ['Miss Monique', 'Proton Sessions 002 (DJ Mix)', '2021'],
          ['Lil Baby', 'The Voice of the Heroes', '2021'],
          ['DaBaby', 'BLAME IT ON BABY (DELUXE)', '2020'],
          ['GUF', 'Дом, который построил Алик', '2020'],
          ['Truwer', 'КАЗ.ПРАВДЫ', '2020'],
          ['Skryptonite', 'THE GENETIC CODE', '2021'],
          ['Young Nudy', 'Rich Shooter', '2021'],
          ['Claptone', 'Closer', '2021'],
          ['DJ Khaled', 'KHALED KHALED', '2021'],
          ['Pooh Shiesty', 'Shiesty Season - Spring Deluxe', '2021'],
          ['Jack Harlow', 'Thats What They All Say', '2020'],
          ['Stunna 4 Vegas', 'Welcome To 4 Vegas', '2020'],
          ['JACKBOYS', 'JACKBOYS', '2019'],
          ['Nicki Minaj', 'Beam Me Up Scotty', '2021']]
